---
# tasks file for post-install

- name: Install ntp agent on ubuntu
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes  # update ubuntu before installing
  when: ansible_distribution == "Ubuntu"
  loop:
    - ntp
    - wget
    - git
    - zip
    - unzip

- name: Install Ntp on centos
  yum:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "CentOS"
  loop:
    - chrony
    - wget
    - git
    - zip
    - unzip

- name: Start service on ubuntu
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Start service on centos
  service:
    name: chronyd  # service name is chronyd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: Banner file
  copy:
    content: '#this server is managed by ansible. No manual changes please.'
    dest: /etc/motd

- name: Create folder  # creating folder here
  file:
    path: "{{ mydir }}"
    state: directory

- name: Deploy ntp agent conf on centos
  template:
    src: ntpconf_centos.j2
    dest: /etc/chrony.conf
    backup: yes
  when: ansible_distribution == "CentOS"
  notify:
    - Restart service on centos

- name: Deploy ntp agent conf on ubuntu
  template:
    src: ntpconf_ubuntu.j2
    dest: /etc/ntpsec/ntp.conf
    backup: yes
  when: ansible_distribution == "Ubuntu"
  notify:
    - Restart service on ubuntu

- name: Dump file  # copy files here
  copy:
    src: myfile.txt
    dest: /tmp/myfile.txt

