---
# handlers file for post-install
- name: Restart service on ubuntu
  service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu"
- name: Restart service on centos
  service:
    name: chronyd  #service name is chronyd
    state: restarted
    enabled: yes
  when: ansible_distribution == "CentOS"

